### ISSUE TITLE
Simpler examples (suggestion)

### ISSUE THREAD

**Issue by intensite** [Baseflow/flutter-blues#1]
May I suggest a simpler example, where a single value would be read from a known device/characteristic and displayed in a label or a textbox.  

Similar to a simple hello world app.

As an added bonus, an example on how to send a numeric value back to the BLE device.

Thanks for this library

**Comment by danielroek** [comment]
Hi @intensite , 

This Flutter plugin is not supported anymore. We recommend using [flutter_reactive_ble.](https://pub.dev/packages/flutter_reactive_ble)

**Comment by intensite** [comment]
@danielroek,  Thank you for the heads-up, I will have a look.
