### ISSUE TITLE
Reconnection avec device reboot ?

### ISSUE THREAD

**Issue by fvisticot** [Baseflow/flutter-blues#2]
Did your library manage the reconnection after device restart on iOs and Android.
With BLE devices, it is mandatory to reconnect device once the smartphone has restarted.

**Comment by danielroek** [comment]
Hi @fvisticot , 

This Flutter plugin is not supported anymore. We recommend using [flutter_reactive_ble.](https://pub.dev/packages/flutter_reactive_ble)
